apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    project: expense
    app: frontend
    tier: web
spec: 
  replicas: 1
  selector:
    matchLabels:
      project: expense
      app: frontend
      tier: web
  template:
    metadata:
      labels: 
        project: expense
        app: frontend
        tier: web
    spec:
      containers:
      - name: frontend
        image: lakshman143/frontend:1.3.0
        ports:
        - containerPort: 8080

---
apiVersion: v1 
kind: Service
metadata: 
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    project: expense
    app: frontend
    tier: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30008

