apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql
  namespace: expense
  labels: 
    project: expense
    app: mysql
    tier: mysql
spec:
  replicas: 1
  selector: 
    matchLabels: 
      project: expense
      app: mysql
      tier: mysql
  template:
    metadata:
      labels: 
        project: expense
        app: mysql
        tier: mysql 
    spec:
      containers:
      - name: mysql
        image: lakshman143/mysql:1.0.0

---
apiVersion: v1 
kind: Service
metadata: 
  name: mysql 
  namespace: expense
spec:
  selector: 
    project: expense
    app: mysql
    tier: mysql 
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    
